[project]
name = "libfoo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "yourname", email = "youremail@example.com" }]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
